# Add your funding links here. GitHub will surface a “Sponsor” button.
# Uncomment and replace placeholders when you are ready.

# GitHub Sponsors (set your username if enabled)
# github: [ 0-danielviktorovich-0 ]

# Other platforms (replace with your own links)
custom:
  - "https://ko-fi.com/your-handle"
  - "https://www.buymeacoffee.com/your-handle"
  - "https://www.patreon.com/your-handle"
  - "https://donationalerts.com/r/your-handle"
