# Add your funding links here. GitHub will surface a “Sponsor” button.
# Uncomment and replace placeholders when you are ready.

# GitHub Sponsors (set your username if enabled)
# github: [ 0-danielviktorovich-0 ]

# Other platforms
ko_fi: danielviktorovich
custom:
  - "https://buymeacoffee.com/danielviktorovich"
