site_name: RimLoc Docs
site_description: Toolkit for working with RimWorld translations
site_url: !ENV [SITE_URL, ""]
repo_url: https://github.com/0-danielviktorovich-0/RimLoc
repo_name: 0-danielviktorovich-0/RimLoc
edit_uri: edit/main/docs/

copyright: "© 2025 RimLoc Project"

use_directory_urls: true

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.integrate
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    language: material/translate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: ru
          name: Русский
          build: true

nav:
  - Repository: https://github.com/0-danielviktorovich-0/RimLoc
  - Home: index.md
  - Start Here:
      - Getting Started: getting-started.md
      - Install: install.md
      - Run Downloaded Build: install_run.md
      - Tutorials:
          - Translate a Mod: tutorials/translate_mod.md
          - Export to PO: tutorials/export_po.md
          - Update Translations: tutorials/update_translations.md
      - Tips & Tricks: tips.md
      - FAQ: faq.md
      - Troubleshooting: troubleshooting.md
      - Glossary: glossary.md
  - CLI:
      - Overview: cli/index.md
      - Scan: cli/scan.md
      - Validate: cli/validate.md
      - Validate PO: cli/validate_po.md
      - Export/Import: cli/export_import.md
      - Build Mod: cli/build_mod.md
      - Diff XML: cli/diff_xml.md
      - Annotate: cli/annotate.md
      - XML Health: cli/xml_health.md
      - Morph: cli/morph.md
      - Init: cli/init.md
      - Lang Update: cli/lang_update.md
  - GUI: guide/gui.md
  - Formats & Concepts:
      - Configuration: guide/configuration.md
      - Placeholders: guide/placeholders.md
      - PO Files 101: guide/po_files.md
      - Learn (Defs/Keyed): learn.md
  - Developers:
      - Overview: dev/index.md
      - Testing: testing.md
  - Community:
      - Discord: community/discord.md
      - Issue Guidelines: community/issues.md
      - Pull Requests: community/pull_requests.md
      - Localization: community/localization.md
      - Support RimLoc: community/support.md

exclude_docs: |
  readme/**

extra:
  edit_uri: edit/main/docs/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/0-danielviktorovich-0/RimLoc
    - icon: fontawesome/brands/rust
      link: https://crates.io/crates/rimloc-cli
    - icon: fontawesome/solid/book
      link: https://0-danielviktorovich-0.github.io/RimLoc/

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
