[package]
name = "rimloc-gui"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "1", features = ["dialog-open", "dialog-save", "shell-open"] }
thiserror = "1"
rimloc-services = { path = "../../../crates/rimloc-services" }
rimloc-domain = { path = "../../../crates/rimloc-domain" }
schemars = { version = "0.8", features = ["schemars_derive"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
