[package]
name = "rimloc-domain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
schemars = { version = "0.8", features = ["schemars_derive"] }

