name: Feature Request
description: Suggest an idea for RimLoc
labels: [enhancement]
body:
  - type: checkboxes
    id: dupcheck
    attributes:
      label: Before submitting
      options:
        - label: I searched open and closed issues/PRs for duplicates
          required: true
        - label: I searched Discussions for prior art
          required: false
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem would this feature solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the change in behavior and CLI/API surface
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
  - type: textarea
    id: examples
    attributes:
      label: Examples and prior art
      description: Commands, flags, or tools that inspired this feature
    validations:
      required: false
  - type: textarea
    id: validation
    attributes:
      label: Validation strategy
      description: How should we test and document this feature?
    validations:
      required: false
  - type: input
    id: related
    attributes:
      label: Related issues/PRs
      description: Links to similar requests or prior attempts
      placeholder: https://github.com/<owner>/<repo>/issues/123
    validations:
      required: false
