[package]
name = "rimloc-core"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
csv = "1.3"
color-eyre = "0.6"