name: changelog

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check changelog updated for user-facing changes
        run: |
          chmod +x scripts/check-changelog.sh
          ./scripts/check-changelog.sh "origin/${{ github.base_ref }}"

