# Deploy is allowed only in the upstream repo to avoid failures in forks.
# Forks still run the build (MkDocs) so maintainers can verify docs compile.
# Preview deploys are skipped for forked PRs (no Pages permissions on GITHUB_TOKEN).
name: docs

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency: pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-docs.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install MkDocs deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt

      - name: Inject site_url for GitHub Pages
        run: |
          sed -i '1isite_url: https://0-danielviktorovich-0.github.io/RimLoc/' mkdocs.yml

      - name: Build site
        run: mkdocs build --verbose --clean

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'danielviktorovich/RimLoc'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

  deploy-preview:
    if: github.event_name == 'pull_request' && github.repository == 'danielviktorovich/RimLoc' && github.event.pull_request.head.repo.fork == false
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true