name: Nightly Dev Pre-release

on:
  push:
    branches: [ develop ]

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
      body: ${{ steps.meta.outputs.body }}
      name: ${{ steps.meta.outputs.name }}
    steps:
      - uses: actions/checkout@v4
      - name: Compute tag and body
        id: meta
        shell: bash
        run: |
          set -euo pipefail
          VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' crates/rimloc-cli/Cargo.toml | head -n1)
          SHORT_SHA=${GITHUB_SHA::7}
          TAG="v${VERSION}-dev.${SHORT_SHA}"
          NAME="Nightly dev pre-release ${TAG}"
          cat > body.txt <<EOF
          Automated dev pre-release build

          Commit: ${GITHUB_SHA}
          Short SHA: ${SHORT_SHA}

          Artifacts:
          - Linux: x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, x86_64-unknown-linux-musl
          - macOS: x86_64-apple-darwin, aarch64-apple-darwin
          - Windows: x86_64-pc-windows-msvc, aarch64-pc-windows-msvc
          EOF
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
          echo "name=${NAME}" >> "$GITHUB_OUTPUT"
          echo "body<<BODY" >> "$GITHUB_OUTPUT"
          cat body.txt >> "$GITHUB_OUTPUT"
          echo "BODY" >> "$GITHUB_OUTPUT"
      - name: Create or update pre-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.name }}
          prerelease: true
          draft: false
          generate_release_notes: true
          body: ${{ steps.meta.outputs.body }}

  linux:
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: Install cross toolchains (Linux)
        if: matrix.target == 'aarch64-unknown-linux-gnu' || matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then sudo apt-get install -y gcc-aarch64-linux-gnu; fi
          if [[ "${{ matrix.target }}" == "x86_64-unknown-linux-musl" ]]; then sudo apt-get install -y musl-tools; fi
      - name: Build (rimloc-cli)
        env:
          CARGO_TERM_COLOR: always
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
        run: |
          cargo build --release -p rimloc-cli --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          set -euo pipefail
          BIN=target/${{ matrix.target }}/release/rimloc-cli
          NAME=rimloc-cli-${{ needs.create_release.outputs.tag }}-${{ matrix.target }}
          mkdir -p dist "$NAME"
          install -m 0755 "$BIN" "$NAME/"
          cp -a README.md LICENSE "$NAME/"
          tar -C "$NAME" -czf "dist/$NAME.tar.gz" .
          echo "Built dist/$NAME.tar.gz"
      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create_release.outputs.tag }}
          files: dist/*

  macos:
    needs: create_release
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: macos-13
            target: x86_64-apple-darwin
          - runs-on: macos-14
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: Build (rimloc-cli)
        run: cargo build --release -p rimloc-cli --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          set -euo pipefail
          BIN=target/${{ matrix.target }}/release/rimloc-cli
          NAME=rimloc-cli-${{ needs.create_release.outputs.tag }}-${{ matrix.target }}
          mkdir -p dist "$NAME"
          install -m 0755 "$BIN" "$NAME/"
          cp -a README.md LICENSE "$NAME/"
          tar -C "$NAME" -czf "dist/$NAME.tar.gz" .
          echo "Built dist/$NAME.tar.gz"
      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create_release.outputs.tag }}
          files: dist/*

  windows:
    needs: create_release
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-msvc, aarch64-pc-windows-msvc]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: Build (rimloc-cli)
        shell: bash
        run: cargo build --release -p rimloc-cli --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          set -euo pipefail
          BIN=target/${{ matrix.target }}/release/rimloc-cli.exe
          NAME=rimloc-cli-${{ needs.create_release.outputs.tag }}-${{ matrix.target }}
          mkdir -p dist "$NAME"
          cp "$BIN" "$NAME/"
          cp -a README.md LICENSE "$NAME/"
          (cd "$NAME" && 7z a -tzip "../dist/$NAME.zip" *)
          echo "Built dist/$NAME.zip"
      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create_release.outputs.tag }}
          files: dist/*

