name: Release-plz

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  release_pr:
    name: Create/Update Release PR
    runs-on: ubuntu-latest
    concurrency:
      group: release-plz-pr-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - name: release-plz (release-pr with PAT)
        if: secrets.RELEASE_PLZ_TOKEN != ''
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
      - name: release-plz (release-pr)
        if: secrets.RELEASE_PLZ_TOKEN == ''
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: release_pr
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    concurrency:
      group: release-plz-release-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - name: release-plz (release with PAT)
        if: secrets.CARGO_REGISTRY_TOKEN != '' && secrets.RELEASE_PLZ_TOKEN != ''
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: release-plz (release)
        if: secrets.CARGO_REGISTRY_TOKEN != '' && secrets.RELEASE_PLZ_TOKEN == ''
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
