[package]
name = "rimloc-plugin-jsonftl"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
description = "Example RimLoc dynamic scan plugin: parse .ftl files"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
